(function(){
'use strict';
const attempted=new Set(),queue=[],images=new Map(),states=new Map();let busy=0;
const safe=value=>{try{const u=new URL(value);return u.protocol==='https:'?u.href:''}catch{return ''}};
function doi(value){const s=String(value||'').trim().replace(/^https?:\/\/(dx\.)?doi\.org\//i,'');return /^10\.\d{4,9}\/\S+$/i.test(s)?s:''}
function key(p){return storageNamespace+'|'+p.id+'|'+doi(p.link).toLowerCase()}
async function get(url,kind){const controller=new AbortController(),t=setTimeout(()=>controller.abort(),25000);try{const r=await fetch(url,{signal:controller.signal});if(!r.ok)throw Error('Image service returned HTTP '+r.status);if(kind==='json')return await r.json();if(kind==='text')return await r.text();const reader=r.body?.getReader();if(!reader){const buffer=await r.arrayBuffer();if(buffer.byteLength>40*1024*1024)throw Error('Image archive is too large');return new Uint8Array(buffer)}let size=0;const chunks=[];while(true){const {done,value}=await reader.read();if(done)break;size+=value.length;if(size>40*1024*1024){await reader.cancel();throw Error('Image archive is too large')}chunks.push(value)}const bytes=new Uint8Array(size);let offset=0;for(const chunk of chunks){bytes.set(chunk,offset);offset+=chunk.length}return bytes;}finally{clearTimeout(t)}}
async function firstFigure(d){
const query=new URL('https://www.ebi.ac.uk/europepmc/webservices/rest/search');query.searchParams.set('query','DOI:"'+d.replace(/"/g,'')+'"');query.searchParams.set('format','json');query.searchParams.set('resultType','core');query.searchParams.set('pageSize','3');const data=await get(query,'json');const p=(data.resultList?.result||[]).find(p=>String(p.doi||'').toLowerCase()===d.toLowerCase());if(!p||p.isOpenAccess!=='Y'||!/^PMC\d+$/.test(p.pmcid||''))throw Error('No open-access full text found');
const base='https://www.ebi.ac.uk/europepmc/webservices/rest/'+p.pmcid;const xml=new DOMParser().parseFromString(await get(base+'/fullTextXML','text'),'application/xml');if(xml.querySelector('parsererror'))throw Error('Full text could not be read');const figure=[...xml.querySelectorAll('fig')].find(f=>/^fig(?:ure)?\.?\s*1\b/i.test(f.querySelector('label')?.textContent.trim()||''));if(!figure)throw Error('Figure 1 was not identified');const graphic=figure.querySelector('graphic');const file=graphic?.getAttributeNS('http://www.w3.org/1999/xlink','href')||graphic?.getAttribute('href');if(!file||file.includes('..'))throw Error('Figure 1 image reference unavailable');
// Official archive includes inline images by default. Match the XML graphic to
// an actual archive entry instead of guessing a public image URL.
const archive=await JSZip.loadAsync(await get(base+'/supplementaryFiles','bytes'));
const basename=file.split('/').pop(),stem=basename.replace(/\.[^.]+$/,'').toLowerCase();
const candidates=Object.values(archive.files).filter(e=>!e.dir&&/\.(png|jpe?g|gif|webp)$/i.test(e.name)&&!e.name.includes('..')).filter(e=>{const n=e.name.split('/').pop().toLowerCase();return n===basename.toLowerCase()||n.replace(/\.[^.]+$/,'')===stem||n.replace(/\.[^.]+$/,'')===basename.toLowerCase()});
if(!candidates.length)throw Error('Figure 1 image is not in the open archive');
candidates.sort((a,b)=>(/\.jpe?g$/i.test(b.name)?1:0)-(/\.jpe?g$/i.test(a.name)?1:0));const entry=candidates[0];if(entry._data?.uncompressedSize>5*1024*1024)throw Error('Figure 1 image is too large');const bytes=await entry.async('uint8array');if(bytes.length>5*1024*1024)throw Error('Figure 1 image is too large');const ext=entry.name.split('.').pop().toLowerCase(),type=ext==='jpg'?'jpeg':ext;return {blob:new Blob([bytes],{type:'image/'+type}),source:'https://europepmc.org/articles/'+p.pmcid,doi:d,label:'Figure 1'};
}
function display(card,p){const panel=card.querySelector('.figure-preview');if(!panel)return;const k=key(p),url=images.get(k);if(url){if(panel.querySelector('img')?.src===url)return;panel.replaceChildren();const img=document.createElement('img');img.src=url;img.alt='Figure 1 from '+p.title;img.onload=()=>{};img.onerror=()=>{states.set(k,'The Figure 1 image could not be displayed');images.delete(k);URL.revokeObjectURL(url);display(card,p)};const caption=document.createElement('span');caption.className='small';caption.textContent='Figure 1 · Europe PMC';panel.append(img,caption);return;}
if(p.figureUrl&&!/^https:\/\/europepmc\.org\/articles\/PMC\d+\/bin\//.test(p.figureUrl))return;
panel.replaceChildren();const text=document.createElement('span');text.className='small';text.textContent=states.get(k)||(!doi(p.link)?'Add a DOI to find Figure 1':'Looking up Figure 1…');panel.append(text);if(attempted.has(k)&&states.get(k)&&!states.get(k).startsWith('Looking')){const retry=document.createElement('button');retry.className='secondary';retry.type='button';retry.textContent='Retry figure';retry.onclick=e=>{e.stopPropagation();attempted.delete(k);states.delete(k);hydrate()};retry.onkeydown=e=>e.stopPropagation();panel.append(retry);}}
function hydrate(){document.querySelectorAll('#cards [data-id]').forEach(card=>{const p=papers.find(p=>p.id===card.dataset.id);if(!p)return;display(card,p);const d=doi(p.link),k=key(p);if((p.figureUrl&&!/^https:\/\/europepmc\.org\/articles\/PMC\d+\/bin\//.test(p.figureUrl))||!d||attempted.has(k)||images.has(k))return;attempted.add(k);states.set(k,'Looking up Figure 1…');queue.push({id:p.id,d,namespace:storageNamespace,k})});pump()}
function pump(){while(busy<2&&queue.length){const job=queue.shift();busy++;(async()=>{try{if(job.namespace!==storageNamespace)return;const figure=await firstFigure(job.d);const p=papers.find(p=>p.id===job.id);if(p&&job.namespace===storageNamespace&&doi(p.link).toLowerCase()===job.d.toLowerCase()){images.set(job.k,URL.createObjectURL(figure.blob));states.delete(job.k);hydrate();}}catch(e){states.set(job.k,e.name==='AbortError'?'Image lookup timed out':e.message||'Could not reach image service');if(job.namespace===storageNamespace)hydrate();}finally{busy--;pump()}})()}}
window.ReadingGardenFigures={hydrate,firstFigure,safe,doi};hydrate();
})();
