(function(){
'use strict';
const attempted=new Set(),queue=[];let busy=0;
const safe=value=>{try{const u=new URL(value);return u.protocol==='https:'?u.href:''}catch{return ''}};
function doi(value){const s=String(value||'').trim().replace(/^https?:\/\/(dx\.)?doi\.org\//i,'');return /^10\.\d{4,9}\/\S+$/i.test(s)?s:''}
async function json(url){const controller=new AbortController(),t=setTimeout(()=>controller.abort(),12000);try{const r=await fetch(url,{signal:controller.signal});if(!r.ok)throw Error();return await r.json()}finally{clearTimeout(t)}}
async function firstFigure(d){const query=new URL('https://www.ebi.ac.uk/europepmc/webservices/rest/search');query.searchParams.set('query','DOI:"'+d.replace(/"/g,'')+'"');query.searchParams.set('format','json');query.searchParams.set('resultType','core');query.searchParams.set('pageSize','3');const data=await json(query);const p=(data.resultList?.result||[]).find(p=>String(p.doi||'').toLowerCase()===d.toLowerCase());if(!p||p.isOpenAccess!=='Y'||!/^PMC\d+$/.test(p.pmcid||''))return null;
const controller=new AbortController(),t=setTimeout(()=>controller.abort(),12000);let xml;try{const r=await fetch('https://www.ebi.ac.uk/europepmc/webservices/rest/'+p.pmcid+'/fullTextXML',{signal:controller.signal});if(!r.ok)return null;xml=new DOMParser().parseFromString(await r.text(),'application/xml')}finally{clearTimeout(t)}
if(xml.querySelector('parsererror'))return null;const figure=[...xml.querySelectorAll('fig')].find(f=>/^fig(?:ure)?\.?\s*1\b/i.test(f.querySelector('label')?.textContent.trim()||''));if(!figure)return null;const g=figure.querySelector('graphic');const file=g?.getAttributeNS('http://www.w3.org/1999/xlink','href')||g?.getAttribute('href');if(!file||file.includes('..')||file.includes('/')||file.includes(':'))return null;
const base='https://europepmc.org/articles/'+p.pmcid+'/bin/';const candidates=[base+encodeURIComponent(file)];if(!/\.(png|jpe?g|gif|webp)$/i.test(file))candidates.push(base+encodeURIComponent(file)+'.jpg',base+encodeURIComponent(file)+'.png');
for(const url of candidates){if(await imageWorks(url))return {url,source:'https://europepmc.org/articles/'+p.pmcid,doi:d,label:'Figure 1'}}return null;}
function imageWorks(url){return new Promise(resolve=>{const image=new Image(),t=setTimeout(()=>finish(false),10000);let ended=false;function finish(ok){if(ended)return;ended=true;clearTimeout(t);image.onload=image.onerror=null;resolve(ok)}image.referrerPolicy='no-referrer';image.onload=()=>finish(image.naturalWidth>0);image.onerror=()=>finish(false);image.src=url})}
function hydrate(){document.querySelectorAll('#cards [data-id]').forEach(card=>{const p=papers.find(p=>p.id===card.dataset.id),d=doi(p?.link);const key=storageNamespace+'|'+p?.id+'|'+d;if(!p||p.figureUrl||!d||attempted.has(key))return;attempted.add(key);queue.push({id:p.id,d,namespace:storageNamespace})});pump()}
function pump(){while(busy<2&&queue.length){const job=queue.shift();busy++;(async()=>{try{if(job.namespace!==storageNamespace)return;const figure=await firstFigure(job.d);const p=papers.find(p=>p.id===job.id);if(figure&&p&&!p.figureUrl&&job.namespace===storageNamespace&&doi(p.link).toLowerCase()===job.d.toLowerCase()){p.figureUrl=figure.url;p.figureSource=figure.source;p.updated=Date.now();persist()}}catch{}finally{busy--;pump()}})()}}
window.ReadingGardenFigures={hydrate,firstFigure,safe,doi};hydrate();
})();
