(function(){
'use strict';
const el=id=>document.getElementById(id),form=el('paperForm');let request=0;
const safe=value=>{try{const u=new URL(value);return u.protocol==='https:'?u.href:''}catch{return ''}};
function doi(value){const s=String(value||'').trim().replace(/^https?:\/\/(dx\.)?doi\.org\//i,'');return /^10\.\d{4,9}\/\S+$/i.test(s)?s:''}
function refresh(){const p=papers.find(p=>p.id===editing);el('privatePdf').hidden=!p?.pdfAttachment;el('privatePdf').textContent=p?.pdfAttachment?'Read uploaded PDF · '+p.pdfAttachment.name:'Read uploaded PDF';el('readOpenPdf').hidden=!safe(form.elements.pdfUrl.value);}
function openEdit(p){request++;el('pdfMessage').textContent='Find an open-access PDF or paste a PDF link.';refresh();if(p&&!p.pdfUrl)find(p.link);}
async function find(value){const id=++request,d=doi(value),original=form.elements.link.value;if(!d||doi(original).toLowerCase()!==d.toLowerCase())return;el('pdfMessage').textContent='Looking for an open-access PDF…';const controller=new AbortController(),timeout=setTimeout(()=>controller.abort(),12000);try{const endpoint=new URL('https://www.ebi.ac.uk/europepmc/webservices/rest/search');endpoint.searchParams.set('query','DOI:"'+d.replace(/"/g,'')+'"');endpoint.searchParams.set('format','json');endpoint.searchParams.set('resultType','core');endpoint.searchParams.set('pageSize','3');const r=await fetch(endpoint,{signal:controller.signal});if(!r.ok)throw Error();const data=await r.json();if(id!==request||!el('editor').open||original!==form.elements.link.value)return;const paper=(data.resultList?.result||[]).find(p=>String(p.doi||'').toLowerCase()===d.toLowerCase());const links=paper?.fullTextUrlList?.fullTextUrl||[];const link=links.find(x=>String(x.documentStyle).toLowerCase()==='pdf'&&String(x.availabilityCode).toUpperCase()==='OA'&&safe(x.url));if(link){if(!form.elements.pdfUrl.value.trim())form.elements.pdfUrl.value=safe(link.url);el('pdfMessage').textContent='Open-access PDF found. Save Record to keep the link.';}else el('pdfMessage').textContent='No open PDF link found. Open the publisher page to read the paper.';refresh();}catch{if(id===request&&el('editor').open)el('pdfMessage').textContent='PDF search is unavailable. You can paste a PDF link.';}finally{clearTimeout(timeout)}}
el('findPdf').onclick=()=>find(form.elements.link.value);el('readOpenPdf').onclick=()=>{const u=safe(form.elements.pdfUrl.value);if(u)window.open(u,'_blank','noopener,noreferrer')};form.elements.pdfUrl.addEventListener('input',refresh);
el('privatePdf').onclick=async()=>{const p=papers.find(p=>p.id===editing);if(!p?.pdfAttachment)return;const tab=window.open('about:blank','_blank');if(tab)tab.opener=null;try{const u=await window.ReadingGardenFiles.open(p.pdfAttachment.path);if(tab)tab.location.replace(u);else el('pdfMessage').textContent='Allow popups, then click Read uploaded PDF again.';}catch(e){if(tab)tab.close();el('pdfMessage').textContent=e.message||'Could not open PDF.'}};
form.addEventListener('reset',()=>{request++;el('pdfMessage').textContent='';});el('editor').addEventListener('close',()=>{request++});
window.ReadingGardenPdf={edit:openEdit,find,safe,doi};
})();

